240531_06_이기영
SeSAC-Flutter-6/learn_dart_together pull request #1
Opened 2024-05-31 06:52 UTC by lgy159

PR 내용에는 자신이 과제를 어떻게 수행했는지, 곤란한 점, 해결못 한 점, 리뷰 받고 싶은 내용 등에 대한 간단한 설명을 작성합니다. 모든 PR에는 모두가 리뷰에 참여할 수 있습니다.

리뷰시 리뷰거리가 없고 따봉을 날리고 싶다면 LGTM 을 코멘트로 작성합니다.

PR 코멘트를 받으면 최대한 수정 반영합니다.

* 과제에서 요구한 부분 단어 하나하나 생각하며 구현했습니다.
* 기능 부분 들은 최대한 짧은 코드로 구현하려 했습니다.
-> 더 괜찮은 코드 있으면 리뷰 부탁드립니다.
* test는 생각나는 모든 test를 진행했습니다.
-> 앞서 질문드린 hp > maxHp는 고려하지 않았습니다.
* 과제에서 요구한 대로 hp, maxHp, mp, maxMP는 모두 초기값을 설정하였지만 test code에서는 가독성을 위해 재지정 하였습니다.

2024-05-31 11:13 UTC, leeseowoo commented on test/cleric_test.dart
> +  });
이 테스트 코드는 실패할 수 있습니다. 확인 부탁드립니다.

2024-05-31 11:24 UTC, leeseowoo commented on test/cleric_test.dart
> +  });
pray()는 회복되는 mp를 반환하고 있고, expect()의 두 번째 인수에 사용된 조건식의 'mp + 1'과 'mp + 3'은 회복된 이후의 mp를 나타내고 있는 것으로 보입니다. result가 조건식의 범위를 벗어나는 경우가 있어서 테스트가 실패하는 경우가 발생할 수 있습니다.

2024-05-31 11:29 UTC, leeseowoo commented on lib/cleric.dart
> +  }
혹시 pray() 호출 시 자신의 mp를 회복해야 한다는 조건은 없었던 걸까요?

2024-05-31 11:59 UTC, leeseowoo commented on test/cleric_test.dart
> +    final cleric = Cleric(name: "클레릭");
클레릭 문자열에만 double quotes를 사용하신 이유가 있을까요?
https://github.com/flutter/flutter/wiki/style-guide-for-flutter-repo#prefer-single-quotes-for-strings
이미 알고 계실 수도 있지만 스타일 가이드 공유드립니다.

2024-05-31 12:28 UTC, lgy159 commented on test/cleric_test.dart
> +  });
말씀하신바 이해하였습니다. 기존 mp와 result를 더한값을 비교해야 한다는 착각이 있었습니다.
테스트를 세분화하여 수정하였습니다. 감사합니다.

2024-05-31 12:28 UTC, lgy159 commented on lib/cleric.dart
> +  }
깜박했습니다. 피드백 감사합니다.

2024-05-31 12:29 UTC, lgy159 commented on test/cleric_test.dart
> +    final cleric = Cleric(name: "클레릭");
습관 때문에 double quotes를 사용해버렸네요. 수정 완료했습니다.

2024-05-31 12:38 UTC, leeseowoo commented on test/cleric_test.dart
> +    final cleric = Cleric(name: "클레릭");
저도 초반에 그랬던 경험이 있습니다 :) 확인해 주셔서 감사합니다.

2024-05-31 16:29 UTC, junsuk5 requested changes

2024-05-31 16:29 UTC, junsuk5 commented on lib/cleric.dart
> +    this.maxMp = 10,
문제에서 최대 hp와 최대 mp 는 변경 가능한 것이 아니고 50, 10으로 고정이기 때문에 생성자에서 지정할 수 없어야 합니다

2024-06-01 16:53 UTC, lgy159 commented on lib/cleric.dart
> +    this.maxMp = 10,
수정 완료하였습니다!

2024-06-04 02:56 UTC, merged