240604_06_이기영
SeSAC-Flutter-6/learn_dart_together pull request #14
Opened 2024-06-04 07:53 UTC by lgy159

* static을 이용하여 cleric을 업그레이드 하였습니다.
* 또한 static을 이용해 매직 넘버를 최소화하였습니다.
-> 잘못 사용했으면 피드백 부탁드립니다.

2024-06-04 23:53 UTC, junsuk5 approved these changes

2024-06-04 23:53 UTC, junsuk5 commented on lib/cleric.dart
> +    final int mpRecovery = praySecond + Random().nextInt(prayRandomValue + 1);
동일 클래스내에서 사용하기 때문에 static 에 접근이 가능하지만
되도록 Cleric.prayRandomValue 로 사용하는 것이 어떨까 싶습니다

2024-06-04 23:53 UTC, junsuk5 commented on lib/cleric.dart
> +  static final int selfAidCost = 5;
좋은 접근입니다

2024-06-05 02:30 UTC, junsuk5 requested changes

2024-06-05 02:30 UTC, junsuk5 commented on lib/cleric.dart
>      required this.name,
틀렸음.
지시사항을 잘 확인하도록.

2024-06-05 06:53 UTC, leeseowoo commented on lib/cleric.dart
> +  static final int selfAidCost = 5;
final을 사용해서 런타임에 변수를 상수로 만들지 않아도 될 것 같다는 생각이 들었습니다. 값이 이미 정해져있기 때문에 컴파일 타임 상수를 사용해도 되지 않을까요? 혹시 final을 사용하신 이유가 따로 있을까요?
static const를 사용할 수 있는데 static final을 사용하여 런타임에 발생할 수 있는 예외를 염두에 두어야 할 것 같습니다. 현재 프로그램에서는 고려하지 않아도 되지만 실행 시점의 사용 가능 메모리와 실행 중 사용 가능 메모리가 다를 수 있기 때문에 큰 데이터를 저장하는 다른 변수들이 많다면 메모리 영역 점유율을 신경 써야 하고 초기화를 위한 일련의 과정에서 발생할 수 있는 예외를 핸들링할 필요가 있을 것 같습니다. 모든 인스턴스가 공유하는 자원이기 때문에 더욱 신경써야 할 것 같네요. 다른 의견이 있다면 말씀 부탁드립니다.

2024-06-05 09:03 UTC, lgy159 commented on lib/cleric.dart
> +    final int mpRecovery = praySecond + Random().nextInt(prayRandomValue + 1);
넵! 안그래도 쓰면서 살짝 의아했습니다. 수정했습니다.

2024-06-05 09:09 UTC, lgy159 commented on lib/cleric.dart
> +  static final int selfAidCost = 5;
그렇군요! 추후 프로젝트에선 static의 사용에 대해 신중하게 생각하겠습니다.
static final을 쓴 이유는 매직 넘버를 최소화하고, test code에서 이를 활용하고 싶었습니다.final 대신 const로 사용했어도 됐겠네요. const와 final를 신경써서 사용해 보겠습니다.

2024-06-05 09:47 UTC, lgy159 commented on lib/cleric.dart
>      required this.name,
생성자의 name부분 때문에 틀렸다고 추측하고있습니다.
문제에서는 "이 클래스는 Cleric() 과 같이 이름을 지정하지 않는 경우에는 인스턴스화 할 수 없다고 한다. (이름이 없는 성직자는 존재 할 수 없음) 생성자는 가능한 한 중복되는 코드가 없도록 작성한다" 라고 서술되어 있는데, required를 붙이면 객체 생성시 필수적으로 name을 입력 받아야 하는걸로 알고 있습니다.

혹시 어떤 부분이 틀렸는지 알 수 있을까요?
중복되는 코드 또한 아니라고 생각됩니다.

2024-06-05 16:40 UTC, junsuk5 commented on lib/cleric.dart
>      required this.name,
문제를 잘 보면 이름은 named parameter를 쓰면 안 됩니다

2024-06-06 09:26 UTC, lgy159 commented on lib/cleric.dart
>      required this.name,
아! 이해했습니다. 수정했습니다. 감사합니다.

2024-06-06 14:47 UTC, merged